### ISSUE TITLE
Lost connection to Station

### ISSUE THREAD

**Issue by EricAgostinelli** [jbasen/WeatherFlow-Tempest-for-Crestron-Home#1]
I've lost connection to the station.   In the Crestron Home Setup app it now says offline.  Everything still works fine via the Weatherflow app.

**Comment by EricAgostinelli** [comment]
Should note that it was functional for about a week or two before it lost the connection.

**Comment by jbasen** [comment]
I checked with the individual who helped test this code during its development and has deployed it with his customers that have Crestron home systems.  He has seen no issues with connectivity.  So, this has to be an issue directly related to your Crestron home processor or home network, not the software itself.   I wish that I could offer more assistance on this topic but I am not an expert in resolving Crestron home processor issues.
