### ISSUE TITLE
Unable to remove prior instances of the extension

### ISSUE THREAD

**Issue by EricAgostinelli** [jbasen/WeatherFlow-Tempest-for-Crestron-Home#2]
After some playing around, I've removed and re-added the extension to the processor.   I am unable to remove old instances of the tile from Crestron Home.  even with removal of the extension in Configurator.

**Comment by jbasen** [comment]
This is a known issue with Crestron extension drivers that I wrote about in an article for Residential Tech Today.  You can find that article here: https://restechtoday.com/a-template-for-writing-a-crestron-home-extension-driver/

There is information in the article on how to avoid the problem and the only method I found for resolving it.

**Comment by EricAgostinelli** [comment]
Resolved the issue by searching and deleting for all traces of the extension in an FTP client and re-loading. Works great again!!

**Comment by jbasen** [comment]
I’m glad that worked out for you. Thanks for reporting your solution
