### ISSUE TITLE
more extensions for weather stations

### ISSUE THREAD

**Issue by chrisp-au** [jbasen/WeatherFlow-Tempest-for-Crestron-Home#4]
Hello,
I was wondering if you are working on extensions for other weather stations?
I am looking for something that is compatible with Australian devices like Holman Aspect Wi-Fi Analyst.

Thanks.

**Comment by jbasen** [comment]
Hi

Unfortunately, I'm not working on any extensions for other weather stations.  CH extensions are challenging and time consuming to write under the best of circumstances and to write one for a  product that I don't have access to would be impossible.
